### ISSUE TITLE
Problems understanding the output files

### ISSUE THREAD

**Issue by zehanna** [xfengnefx/hifiasm-meta#10]
Hello,

I'm testing hifiasm for my PacBio Hifi reads. Running the program works fine, however I'm having some problems making sense of the output files. With other assemblers such as hiCanu and flye, you get one fasta file that contains the complete assembly, to which the reads can be mapped to.
With hifiasm, you get multiple unitig and contig output files (the asm.a*, asm.r*, and asm.p* files, in addition the *noseq* versions) in GFA format. These are all the GFA files that I got:

asm.a_ctg.gfa        
asm.p_ctg.noseq.gfa  
asm.p_utg.noseq.gfa  
asm.r_utg.noseq.gfa
asm.a_ctg.noseq.gfa  
asm.p_ctg.gfa        
asm.p_utg.gfa        
asm.r_utg.gfa  

Could you tell me which of these files corresponds most to the one assembly.fasta that is produced by other assemblers?
This one I want to use for further analysis, such as mapping of the reads and binning.

Thanks a lot for any help,

Hanna

**Comment by xfengnefx** [comment]
The final assembly is the `p_ctg`, with `a_ctg` as the alternative graph (popped bubble edges etc are in this file, probably useless though). `r_utg` is the raw unitig graph, i.e. after transitive reduction but no graph cleaning. You can ignore `p_utg`. The `noseq` ones are identical to their counterparts except for not having sequences.

To get a fasta for an assembly, extract the 2nd and 3rd columns of S lines from a not-noseq gfa. In bash you can do: 

- get all contigs: `cat asm.p_ctg.gfa | awk '$1=="S" {printf ">%s\n%s\n", $2, $3} ' | gzip -1 > asm.fa.gz`

- get only circular contigs: `cat asm.p_ctg.gfa | awk '$1=="S" && ($2 ~ /.c$/) {printf ">%s\n%s\n", $2, $3} ' | gzip -1 > asm_circ.fa.gz`

**Comment by zehanna** [comment]
Thanks a lot for your quick answer, it was really helpful!
