### ISSUE TITLE
Update bioconda recipe to latest release

### ISSUE THREAD

**Issue by fplazaonate** [xfengnefx/hifiasm-meta#14]
Hello,

Could you update the bioconda recipe to the the latest release?  (current version is v0.2 r40 instead of v0.2.1 r52)

Thanks!

**Comment by xfengnefx** [comment]
Hi, thanks for the reminder. I have created a pull request for the current HEAD (r57 or v0.2.2) over there. Waiting for checks and merge.

**Comment by xfengnefx** [comment]
Merged: https://github.com/bioconda/bioconda-recipes/pull/32761 .
