### ISSUE TITLE
A serious error in simulated data

### ISSUE THREAD

**Issue by ruoyu1123** [xfengnefx/hifiasm-meta#16]
### [*** stack smashing detected ***]
When a data set have a high coverage, the error maybe appear.  The software for simulation is pbsim2.

**Comment by xfengnefx** [comment]
What's the target coverage? Could you post the log file (stderr)? I wonder where did this stack smashing happen..

Also for pbsim2, I think its default settings does not simulate hifi reads, is that correct?

**Comment by ruoyu1123** [comment]
> What's the target coverage? Could you post the log file (stderr)? I wonder where did this stack smashing happen..
> 
> Also for pbsim2, I think its default settings does not simulate hifi reads, is that correct?
Sorry, It is my careless. There are many letter  outside of [ATCG] in reference of simulation , such as Z, Y, H and so on. So，the program had this error. Now, the problem have been solved.  Thank you.
