### ISSUE TITLE
在不去除宿主的情况下，能否组装到宿主基因组

### ISSUE THREAD

**Issue by ye00ye** [xfengnefx/hifiasm-meta#18]
如题，我想咨询一下，在对原始序列不进行去除宿主污染的情况下，该软件能否组装到宿主基因组

**Comment by xfengnefx** [comment]
I think contaminations would not matter too much, becuase sequence similarity should be low. I suggest you assemble and see how it goes.

**Comment by ye00ye** [comment]
Thanks you for your helping, i will try.


| |
ye--ye
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年8月30日 21:38 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [xfengnefx/hifiasm-meta] 在不去除宿主的情况下，能否组装到宿主基因组 (Issue #18) |

I think contaminations would not matter too much, becuase sequence similarity should be low. I suggest you assemble and see how it goes.
