### ISSUE TITLE
gfa s-line

### ISSUE THREAD

**Issue by liushanlin** [xfengnefx/hifiasm-meta#20]
Hello,

Could you please explain more about the S-line of the noseq.gfa file. 
What does "dp" and "ts" represent for, respectively.

thank you.

**Comment by xfengnefx** [comment]
Sorry for the late reply. `dp` is estimated coverage for the contig, it is based on counting reads. For longer contigs, this would be somewhat consistent to alignment-based estimation. Listed as a float but currently will be filled with integers. 

`ts` is "trailing subgraph labels". Longer the array is, more graph cleaning operations have happened to the subgraph currently containing the contig. I thought to use them as crude hints about heterogeneity, but I think they are mostly useless and read mapping is more appropriate. The final subgraph IDs of the contigs are contained in contig names (^s[0-9]+).

**Comment by liushanlin** [comment]
> Sorry for the late reply. `dp` is estimated coverage for the contig, it is based on counting reads. For longer contigs, this would be somewhat consistent to alignment-based estimation. Listed as a float but currently will be filled with integers.
> 
> `ts` is "trailing subgraph labels". Longer the array is, more graph cleaning operations have happened to the subgraph currently containing the contig. I thought to use them as crude hints about heterogeneity, but I think they are mostly useless and read mapping is more appropriate. The final subgraph IDs of the contigs are contained in contig names (^s[0-9]+).

Many thanks for those details.
