### ISSUE TITLE
New release for r73 and binning

### ISSUE THREAD

**Issue by cjfields** [xfengnefx/hifiasm-meta#36]
Would it be possible to tag a new release for the recent updates for the binning publication?

https://genomebiology.biomedcentral.com/articles/10.1186/s13059-024-03234-6

The paper mentions r73, but the latest tagged release is r63.2.  We're using the Biocontainer Docker version of hifiasm-meta, which seems to be tied to the releases made.  Thanks!

**Comment by xfengnefx** [comment]
Hi, sorry for the lack of updates. I have merged a performance patch from dev branch and made a release. Bioconda PR is under review [here](https://github.com/bioconda/bioconda-recipes/pull/50862), hopefully will go live soon :) edit: merged.
