### ISSUE TITLE
Output files for binning

### ISSUE THREAD

**Issue by YannDussert** [xfengnefx/hifiasm-meta#37]
Hi,

Thanks for developing hifiasm-meta!

I had a question about output files for the binning procedure described in https://doi.org/10.1186/s13059-024-03234-6. Bins are put into the hifiasm-meta.bins.tsv file, but  > 1Mb circular contigs are considered as "complete" genomes and are not in this file, correct?

I was also wondering what is written in the asm.rescue.all.fa and asm.rescue.fa files?

Thanks in advance for your reply!

Best regards,
Yann

**Comment by xfengnefx** [comment]
Hi, 

Thanks for trying it out! :) 

> the hifiasm-meta.bins.tsv file

\>=1Mb circular contigs are not used in the binning, they should not show up in this file. And also see below.

> asm.rescue.all.fa and asm.rescue.fa files

These are the "circle finding" in the manuscript. After assembly, there are two binning heuristics. The circle finding runs first, which basically does depth first searches on the contig graph (details in the manuscript). The DFS has heuristics to discourage it from reporting multiple paths that belong to the same species (either of these are not fully haplotype-resolved anyways), but it along is not enough, so after all DFS searches there is another mesh-like deduplication. 

`asm.rescue.all.fa` contains all circular paths reported by this search. Probably not useful. `asm.rescue.fa` is the paths after the mesh-like deduplication. 

The second binning heuristic is tSNE-based and produces the prefix.bins.tsv file. Contigs >=100kb that are already used in the `asm.rescue.fa` will be excluded from this file, too.

With these built-in binnings, the reported MAGs are the union of the follow, which need then go through quality checks such as checkM: 
- \>=1Mb circular contigs from contig gfa
- asm.rescue.fa
- contig sets as described in the asm.bins.tsv

**Comment by YannDussert** [comment]
Thank you for the information!

Yann

**Comment by cjfields** [comment]
@xfengnefx just to add a quick question on this.  Based on your description above:

> With these built-in binnings, the reported MAGs are the union of the follow, which need then go through quality checks such as checkM:
> 
> * >=1Mb circular contigs from contig gfa
> * asm.rescue.fa
> * contig sets as described in the asm.bins.tsv

As these are specifically MAGs, my read of this is that any remaining contigs in the GFA (those _not_ found in the other files) may (1) either need to be separately binned, or (2) bin everything together but split out the MAGs predicted from the above set (of course w/ QC check using CheckM).  Is that a fair interpretation?

**Comment by xfengnefx** [comment]
@cjfields Sorry for the late reply. That's right. You can also use these three together as the MAGs (and run no other binning workflows), and simply treat unused contigs as not bin-able, but the following was better in the datasets we tested: run metabat2 on all contigs -> pick out 1Mb circular contigs from metabat2 bins -> merge with asm.rescue.fa (which picks up some MAGs that have tiny contigs & metabat2 cannot reliably bin) with deduplication. 

I did not test whether letting metabat2 or other binners work on the subset of contigs (i.e. contigs used by any of the three MAG collections removed) could be better. I think that might be worse if contig coverages are skewed by the removal.

**Comment by cjfields** [comment]
> I did not test whether letting metabat2 or other binners work on the subset of contigs (i.e. contigs used by any of the three MAG collections removed) could be better. I think that might be worse if contig coverages are skewed by the removal.

Awesome, thx @xfengnefx !  I agree, I suspect removing contigs prior to determining coverage on the remaining ones would not be beneficial, it makes more sense to do the binning on all data and postprocess afterwards like you mentioned.
