### ISSUE TITLE
Good settings for enriched similar sequences

### ISSUE THREAD

**Issue by suzukimicro** [xfengnefx/hifiasm-meta#6]
Hi,
We are struggling to perform de novo assembly of meta bacterial samples selectively cultured with antimicrobials from wasterwater using hifiasm-meta with the default parameters. The sequencing depth seemed to be fine, but the number of circulated bacterial genomes and plasmids is not large, so the resulted contigs would not be good. We guess the cause might be due to the increased redundancy of sequences (bacterial species and plasmids). Someone knows if there are any effective settings to deal with this kind of data?
Thanks!

**Comment by xfengnefx** [comment]
What's the library size? Could you share the log file (stderr)? Maybe you can try a run with `-A` using the previous bin files. This does a slightly more aggressive local graph cleaning, would help if you already get circle-ish tangled subgraphs in [bandage](https://github.com/rrwick/Bandage/) layout, but probably not useful otherwise.

**Comment by lh3** [comment]
> the number of circulated bacterial genomes and plasmids is not large

Just curious: what's the number?

**Comment by suzukimicro** [comment]
> What's the library size? Could you share the log file (stderr)? Maybe you can try a run with `-A` using the previous bin files. This does a slightly more aggressive local graph cleaning, would help if you already get circle-ish tangled subgraphs in [bandage](https://github.com/rrwick/Bandage/) layout, but probably not useful otherwise.

Thank you for your suggestion. We will try it.
Here are the summary of our hifiasm_meta analysis and the log file.

[Hifiasm_meta_p_ctg.pdf](https://github.com/xfengnefx/hifiasm-meta/files/7312169/Hifiasm_meta_p_ctg.pdf)
![Hifiasm_meta_p_ctg](https://user-images.githubusercontent.com/47552884/136577990-9f3aa6aa-5263-4d64-a47f-4576940c866a.jpg)
[Hifiasm_meta.log](https://github.com/xfengnefx/hifiasm-meta/files/7312172/Hifiasm_meta.log)

**Comment by suzukimicro** [comment]
> > the number of circulated bacterial genomes and plasmids is not large
> 
> Just curious: what's the number?

Thank you for your comment. In this case, the number of circular contigs were 50.

**Comment by xfengnefx** [comment]
I saw you're using r40, so please pull and make before the `-A` rerun - it was introduced later. The newer revisions also had some bug fixes. 

Thanks for the bandage plot. Since you mentioned the sample was selectively cultured, is there any strain or genera that you expect to see in the assembly, but is not assembled well? The graph looks pretty clean to me. For the disconnected linear contigs (4th row in the bandage plot, I guess those are in the 300kb-1Mb range?), maybe you can have a look at their `ts:B` tag in gfa `S` lines, or just plot `*r_utg.nose.gfa` with bandage. My guess is the tags are short in length, and the unitig graph plot has roughly the same overall structure compared to the p_ctg one.

**Comment by xfengnefx** [comment]
> > > the number of circulated bacterial genomes and plasmids is not large
> > 
> > 
> > Just curious: what's the number?
> 
> Thank you for your comment. In this case, the number of circular contigs were 50.

A side note: some small circular ones may be plasmids. In a mock dataset we were able to confirm some thanks to the reference. However, it was hard to directly evaluate in real datasets. I would love to learn if there's any robust way to do the quality check...

**Comment by suzukimicro** [comment]
> I saw you're using r40, so please pull and make before the `-A` rerun - it was introduced later. The newer revisions also had some bug fixes.
> 
> Thanks for the bandage plot. Since you mentioned the sample was selectively cultured, is there any strain or genera that you expect to see in the assembly, but is not assembled well? The graph looks pretty clean to me. For the disconnected linear contigs (4th row in the bandage plot, I guess those are in the 300kb-1Mb range?), maybe you can have a look at their `ts:B` tag in gfa `S` lines, or just plot `*r_utg.nose.gfa` with bandage. My guess is the tags are short in length, and the unitig graph plot has roughly the same overall structure compared to the p_ctg one.

Thank you for your kind help. Let you know the result.

> A side note: some small circular ones may be plasmids. In a mock dataset we were able to confirm some thanks to the reference. However, it was hard to directly evaluate in real datasets. I would love to learn if there's any robust way to do the quality check...

We want to analyze AMR-associated plasmids. That's why we selected environmental bacteria by antimicrobials. For plasmids, there would be no tool to evaluate completeness, such as CheckM and CheckV. Examination of circular contigs and the presence of plasmid replicon genes (can be detected by [MOB-typer](https://github.com/phac-nml/mob-suite))  would be evaluation methods for assembly. We can provide our raw data if it would help improving the development of this wonderful program.

**Comment by xfengnefx** [comment]
I see. Plasmids are tricky..

Would be great if you can share the readset set with us. We will use it only for method developement. My mail is `xfeng (at) ds.dfci.harvard.edu` if you would like to bring the conversation there, thanks!
