### ISSUE TITLE
Hi-C integration?

### ISSUE THREAD

**Issue by olekto** [xfengnefx/hifiasm-meta#7]
Hi,
are you back-porting (up-porting? side-porting?) the Hi-C integration from hifiasm? We are sequencing some species where up to half the sample might be bacteria and fungi (the target species is a plant), and are considering using hifiasm-meta for this as the first step, and then mapping and extracting the plant-specific reads for a separate assembly with regular hifiasm. We are also getting Hi-C reads for these samples, so I wondered if Hi-C integration might be helpful for separating species in hifiasm-meta.

Sincerely,
Ole

**Comment by xfengnefx** [comment]
I think porting Hi-C mode should be fine although not trivial. We are not doing that at the moment becuase even hifi datasets are not abundant for metagenome, and only one of them has Hi-C. Also none of them have had significant host(?) contamination.

For your use case, I _guess_ that to filter contigs belong tobacteria/fungi, checkM/rRNA/gene-based approach (e.g. mmseqs2 taxonomy workflow) is the way to go. Except in mock datasets, only some strains/species could be recovered as complete circular genomes, others are tangled/fragmented/unconnected. 

Actually I'm not sure if the hifiasm-meta+alignment step could improve the final plant assembly. For the plant, I would assemble with the regular hifiasm first and see what comes out.

**Comment by olekto** [comment]
Thank you for your advice. I'll try some different approaches and see what works best.

**Comment by lh3** [comment]
The hifiasm Hi-C phasing assumes the sample is diploid. Lifting this assumption is non-trivial and may actually need a new algorithm.
