### ISSUE TITLE
No circular contigs recovered

### ISSUE THREAD

**Issue by fplazaonate** [xfengnefx/hifiasm-meta#9]
Hi,

I have tested hifiasm-meta on a pacbio hifi data obtained from fecal metagenome of a healthy human.

Below are the library statistics:
```
sum = 13017330229, n = 1646208, ave = 7907.46, largest = 21324
N50 = 8596, n = 605631
N60 = 7871, n = 763863
N70 = 7149, n = 937306
N80 = 6377, n = 1129752
N90 = 5392, n = 1350332
N100 = 104, n = 1646208
```

Below are the assembly statistics (asm.p_ctg.gfa):
```
sum = 831324548, n = 15560, ave = 53427.03, largest = 3704035
N50 = 132051, n = 896
N60 = 73324, n = 1769
N70 = 45743, n = 3226
N80 = 29874, n = 5501
N90 = 19672, n = 8924
N100 = 2682, n = 15560
```

Unfortunately, it seems that there are no circular contigs even if some contigs are very long (>3Mb)
Here is a this screenshot:
![image](https://user-images.githubusercontent.com/4588656/141420438-fe031e70-b417-44d0-8e2b-1b117f087cb0.png)

Is there something i'm doing wrong ?

Thanks for your help,
Florian

**Comment by xfengnefx** [comment]
I'm not sure. The human fecal libraries we've tested all produced graphs with a large tangled subgraph, then everything else (circular/linear/smaller subgraphs). Yours is surprising for a 13G library. I've only seen a graph looking like this once in an exotic test dataset (iirc ~~also~~ pretty small), but we didn't have the permission to check more closely.

Could you plot the r_utg graph with bandage as well? And do you have the log file (stderr)?

**Comment by fplazaonate** [comment]
Here is the r_utg graph imported in bandage:
![image](https://user-images.githubusercontent.com/4588656/141429978-73bc012d-d53f-41cc-a78f-f0d02432cce1.png)

I will re-run the tool and save the log.

**Comment by fplazaonate** [comment]
I have reloaded the gfa file with the latest version of Bandage.
Not sure what I did wrong but the graph looks like what is expected now :
![image](https://user-images.githubusercontent.com/4588656/141433155-8d32c853-f9a8-4e98-a990-8aaf146ad181.png)

Sorry for the inconvenience and thanks for this great tool!

**Comment by xfengnefx** [comment]
By the way, to get circular contigs you can grep the contigs with names end with 'c', no need to check bandage plot for that. Currently (r51) there's a small bug that very occasionally fails to name it correctly (no false positives though), will be fixed in the next push/release.

**Comment by fplazaonate** [comment]
Thanks for the tip. I will wait for the next release then.
